/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenApiJs) {
      root.AdyenApiJs = {};
    }
    root.AdyenApiJs.Address = factory(root.AdyenApiJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Address model module.
   * @module model/Address
   * @version 1.30.4
   */

  /**
   * Constructs a new <code>Address</code>.
   * the address where to send the invoice
   * @alias module:model/Address
   * @class
   * @param city {String} the city
   * @param country {String} the two letter country code (ISO 3166-1)
   * @param houseNumberOrName {String} the house number or name
   * @param street {String} the street name
   */
  var exports = function(city, country, houseNumberOrName, street) {
    var _this = this;

    _this['city'] = city;
    _this['country'] = country;
    _this['houseNumberOrName'] = houseNumberOrName;


    _this['street'] = street;
  };

  /**
   * Constructs a <code>Address</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Address} obj Optional instance to populate.
   * @return {module:model/Address} The populated <code>Address</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('city')) {
        obj['city'] = ApiClient.convertToType(data['city'], 'String');
      }
      if (data.hasOwnProperty('country')) {
        obj['country'] = ApiClient.convertToType(data['country'], 'String');
      }
      if (data.hasOwnProperty('houseNumberOrName')) {
        obj['houseNumberOrName'] = ApiClient.convertToType(data['houseNumberOrName'], 'String');
      }
      if (data.hasOwnProperty('postalCode')) {
        obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
      }
      if (data.hasOwnProperty('stateOrProvince')) {
        obj['stateOrProvince'] = ApiClient.convertToType(data['stateOrProvince'], 'String');
      }
      if (data.hasOwnProperty('street')) {
        obj['street'] = ApiClient.convertToType(data['street'], 'String');
      }
    }
    return obj;
  }

  /**
   * the city
   * @member {String} city
   */
  exports.prototype['city'] = undefined;
  /**
   * the two letter country code (ISO 3166-1)
   * @member {String} country
   */
  exports.prototype['country'] = undefined;
  /**
   * the house number or name
   * @member {String} houseNumberOrName
   */
  exports.prototype['houseNumberOrName'] = undefined;
  /**
   * the postal / zip code
   * @member {String} postalCode
   */
  exports.prototype['postalCode'] = undefined;
  /**
   * the state or province
   * @member {String} stateOrProvince
   */
  exports.prototype['stateOrProvince'] = undefined;
  /**
   * the street name
   * @member {String} street
   */
  exports.prototype['street'] = undefined;


  /**
   * Returns the city
   * @return {String}
   */
  exports.prototype.getCity = function() {
    return this['city'];
  }

  /**
   * Sets the city
   * @param {String} city the city
   */
  exports.prototype.setCity = function(city) {
    this['city'] = city;
  }


  /**
   * Returns the two letter country code (ISO 3166-1)
   * @return {String}
   */
  exports.prototype.getCountry = function() {
    return this['country'];
  }

  /**
   * Sets the two letter country code (ISO 3166-1)
   * @param {String} country the two letter country code (ISO 3166-1)
   */
  exports.prototype.setCountry = function(country) {
    this['country'] = country;
  }


  /**
   * Returns the house number or name
   * @return {String}
   */
  exports.prototype.getHouseNumberOrName = function() {
    return this['houseNumberOrName'];
  }

  /**
   * Sets the house number or name
   * @param {String} houseNumberOrName the house number or name
   */
  exports.prototype.setHouseNumberOrName = function(houseNumberOrName) {
    this['houseNumberOrName'] = houseNumberOrName;
  }


  /**
   * Returns the postal / zip code
   * @return {String}
   */
  exports.prototype.getPostalCode = function() {
    return this['postalCode'];
  }

  /**
   * Sets the postal / zip code
   * @param {String} postalCode the postal / zip code
   */
  exports.prototype.setPostalCode = function(postalCode) {
    this['postalCode'] = postalCode;
  }


  /**
   * Returns the state or province
   * @return {String}
   */
  exports.prototype.getStateOrProvince = function() {
    return this['stateOrProvince'];
  }

  /**
   * Sets the state or province
   * @param {String} stateOrProvince the state or province
   */
  exports.prototype.setStateOrProvince = function(stateOrProvince) {
    this['stateOrProvince'] = stateOrProvince;
  }


  /**
   * Returns the street name
   * @return {String}
   */
  exports.prototype.getStreet = function() {
    return this['street'];
  }

  /**
   * Sets the street name
   * @param {String} street the street name
   */
  exports.prototype.setStreet = function(street) {
    this['street'] = street;
  }



  return exports;
}));


