/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenApiJs) {
      root.AdyenApiJs = {};
    }
    root.AdyenApiJs.BrowserInfo = factory(root.AdyenApiJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BrowserInfo model module.
   * @module model/BrowserInfo
   * @version 1.30.3
   */

  /**
   * Constructs a new <code>BrowserInfo</code>.
   * the browser info data
   * @alias module:model/BrowserInfo
   * @class
   * @param userAgent {String} the user agent value of the shopper's browser
   * @param acceptHeader {String} the accept header value of the shopper's browser
   */
  var exports = function(userAgent, acceptHeader) {
    var _this = this;

    _this['userAgent'] = userAgent;
    _this['acceptHeader'] = acceptHeader;
  };

  /**
   * Constructs a <code>BrowserInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BrowserInfo} obj Optional instance to populate.
   * @return {module:model/BrowserInfo} The populated <code>BrowserInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('userAgent')) {
        obj['userAgent'] = ApiClient.convertToType(data['userAgent'], 'String');
      }
      if (data.hasOwnProperty('acceptHeader')) {
        obj['acceptHeader'] = ApiClient.convertToType(data['acceptHeader'], 'String');
      }
    }
    return obj;
  }

  /**
   * the user agent value of the shopper's browser
   * @member {String} userAgent
   */
  exports.prototype['userAgent'] = undefined;
  /**
   * the accept header value of the shopper's browser
   * @member {String} acceptHeader
   */
  exports.prototype['acceptHeader'] = undefined;


  /**
   * Returns the user agent value of the shopper's browser
   * @return {String}
   */
  exports.prototype.getUserAgent = function() {
    return this['userAgent'];
  }

  /**
   * Sets the user agent value of the shopper's browser
   * @param {String} userAgent the user agent value of the shopper's browser
   */
  exports.prototype.setUserAgent = function(userAgent) {
    this['userAgent'] = userAgent;
  }


  /**
   * Returns the accept header value of the shopper's browser
   * @return {String}
   */
  exports.prototype.getAcceptHeader = function() {
    return this['acceptHeader'];
  }

  /**
   * Sets the accept header value of the shopper's browser
   * @param {String} acceptHeader the accept header value of the shopper's browser
   */
  exports.prototype.setAcceptHeader = function(acceptHeader) {
    this['acceptHeader'] = acceptHeader;
  }



  return exports;
}));


