/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Contract'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Contract'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenApiJs) {
      root.AdyenApiJs = {};
    }
    root.AdyenApiJs.DisableRequest = factory(root.AdyenApiJs.ApiClient, root.AdyenApiJs.Contract);
  }
}(this, function(ApiClient, Contract) {
  'use strict';




  /**
   * The DisableRequest model module.
   * @module model/DisableRequest
   * @version 1.30.5
   */

  /**
   * Constructs a new <code>DisableRequest</code>.
   * @alias module:model/DisableRequest
   * @class
   * @param merchantAccount {String} Your merchant account.
   * @param shopperReference {String} The ID that uniquely identifies the shopper. This `shopperReference` must be the same as the `shopperReference` used in the initial payment.
   */
  var exports = function(merchantAccount, shopperReference) {
    var _this = this;


    _this['merchantAccount'] = merchantAccount;

    _this['shopperReference'] = shopperReference;
  };

  /**
   * Constructs a <code>DisableRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DisableRequest} obj Optional instance to populate.
   * @return {module:model/DisableRequest} The populated <code>DisableRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('contract')) {
        obj['contract'] = Contract.constructFromObject(data['contract']);
      }
      if (data.hasOwnProperty('merchantAccount')) {
        obj['merchantAccount'] = ApiClient.convertToType(data['merchantAccount'], 'String');
      }
      if (data.hasOwnProperty('recurringDetailReference')) {
        obj['recurringDetailReference'] = ApiClient.convertToType(data['recurringDetailReference'], 'String');
      }
      if (data.hasOwnProperty('shopperReference')) {
        obj['shopperReference'] = ApiClient.convertToType(data['shopperReference'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Contract} contract
   */
  exports.prototype['contract'] = undefined;
  /**
   * Your merchant account.
   * @member {String} merchantAccount
   */
  exports.prototype['merchantAccount'] = undefined;
  /**
   * The ID that uniquely identifies the recurring detail reference. If it is not provided, the whole recurring contract of the `shopperReference` will be disabled, which includes all recurring details.
   * @member {String} recurringDetailReference
   */
  exports.prototype['recurringDetailReference'] = undefined;
  /**
   * The ID that uniquely identifies the shopper. This `shopperReference` must be the same as the `shopperReference` used in the initial payment.
   * @member {String} shopperReference
   */
  exports.prototype['shopperReference'] = undefined;


  /**
   * @return {module:model/Contract}
   */
  exports.prototype.getContract = function() {
    return this['contract'];
  }

  /**
   * @param {module:model/Contract} contract
   */
  exports.prototype.setContract = function(contract) {
    this['contract'] = contract;
  }


  /**
   * Returns Your merchant account.
   * @return {String}
   */
  exports.prototype.getMerchantAccount = function() {
    return this['merchantAccount'];
  }

  /**
   * Sets Your merchant account.
   * @param {String} merchantAccount Your merchant account.
   */
  exports.prototype.setMerchantAccount = function(merchantAccount) {
    this['merchantAccount'] = merchantAccount;
  }


  /**
   * Returns The ID that uniquely identifies the recurring detail reference. If it is not provided, the whole recurring contract of the `shopperReference` will be disabled, which includes all recurring details.
   * @return {String}
   */
  exports.prototype.getRecurringDetailReference = function() {
    return this['recurringDetailReference'];
  }

  /**
   * Sets The ID that uniquely identifies the recurring detail reference. If it is not provided, the whole recurring contract of the `shopperReference` will be disabled, which includes all recurring details.
   * @param {String} recurringDetailReference The ID that uniquely identifies the recurring detail reference. If it is not provided, the whole recurring contract of the `shopperReference` will be disabled, which includes all recurring details.
   */
  exports.prototype.setRecurringDetailReference = function(recurringDetailReference) {
    this['recurringDetailReference'] = recurringDetailReference;
  }


  /**
   * Returns The ID that uniquely identifies the shopper. This `shopperReference` must be the same as the `shopperReference` used in the initial payment.
   * @return {String}
   */
  exports.prototype.getShopperReference = function() {
    return this['shopperReference'];
  }

  /**
   * Sets The ID that uniquely identifies the shopper. This `shopperReference` must be the same as the `shopperReference` used in the initial payment.
   * @param {String} shopperReference The ID that uniquely identifies the shopper. This `shopperReference` must be the same as the `shopperReference` used in the initial payment.
   */
  exports.prototype.setShopperReference = function(shopperReference) {
    this['shopperReference'] = shopperReference;
  }



  return exports;
}));


