/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ErrorType'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenApiJs) {
      root.AdyenApiJs = {};
    }
    root.AdyenApiJs.Error = factory(root.AdyenApiJs.ApiClient, root.AdyenApiJs.ErrorType);
  }
}(this, function(ApiClient, ErrorType) {
  'use strict';




  /**
   * The Error model module.
   * @module model/Error
   * @version 1.30.4
   */

  /**
   * Constructs a new <code>Error</code>.
   * @alias module:model/Error
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Error</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Error} obj Optional instance to populate.
   * @return {module:model/Error} The populated <code>Error</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('errorCode')) {
        obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'String');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('errorType')) {
        obj['errorType'] = ErrorType.constructFromObject(data['errorType']);
      }
    }
    return obj;
  }

  /**
   * the HTTP response status code
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * the Adyen code thatt is mapped to the error message
   * @member {String} errorCode
   */
  exports.prototype['errorCode'] = undefined;
  /**
   * the message, a short explanation of the issue
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * @member {module:model/ErrorType} errorType
   */
  exports.prototype['errorType'] = undefined;


  /**
   * Returns the HTTP response status code
   * @return {String}
   */
  exports.prototype.getStatus = function() {
    return this['status'];
  }

  /**
   * Sets the HTTP response status code
   * @param {String} status the HTTP response status code
   */
  exports.prototype.setStatus = function(status) {
    this['status'] = status;
  }


  /**
   * Returns the Adyen code thatt is mapped to the error message
   * @return {String}
   */
  exports.prototype.getErrorCode = function() {
    return this['errorCode'];
  }

  /**
   * Sets the Adyen code thatt is mapped to the error message
   * @param {String} errorCode the Adyen code thatt is mapped to the error message
   */
  exports.prototype.setErrorCode = function(errorCode) {
    this['errorCode'] = errorCode;
  }


  /**
   * Returns the message, a short explanation of the issue
   * @return {String}
   */
  exports.prototype.getMessage = function() {
    return this['message'];
  }

  /**
   * Sets the message, a short explanation of the issue
   * @param {String} message the message, a short explanation of the issue
   */
  exports.prototype.setMessage = function(message) {
    this['message'] = message;
  }


  /**
   * @return {module:model/ErrorType}
   */
  exports.prototype.getErrorType = function() {
    return this['errorType'];
  }

  /**
   * @param {module:model/ErrorType} errorType
   */
  exports.prototype.setErrorType = function(errorType) {
    this['errorType'] = errorType;
  }



  return exports;
}));


