/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenApiJs) {
      root.AdyenApiJs = {};
    }
    root.AdyenApiJs.EventCode = factory(root.AdyenApiJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class EventCode.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "AUTHORISATION"
     * @const
     */
    "AUTHORISATION": "AUTHORISATION",
    /**
     * value: "CANCELLATION"
     * @const
     */
    "CANCELLATION": "CANCELLATION",
    /**
     * value: "REFUND"
     * @const
     */
    "REFUND": "REFUND",
    /**
     * value: "CANCEL_OR_REFUND"
     * @const
     */
    "CANCEL_OR_REFUND": "CANCEL_OR_REFUND",
    /**
     * value: "AUTHORISATION_ADJUSTMENT"
     * @const
     */
    "AUTHORISATION_ADJUSTMENT": "AUTHORISATION_ADJUSTMENT",
    /**
     * value: "CAPTURE"
     * @const
     */
    "CAPTURE": "CAPTURE",
    /**
     * value: "CAPTURE_FAILED"
     * @const
     */
    "CAPTURE_FAILED": "CAPTURE_FAILED",
    /**
     * value: "REFUND_FAILED"
     * @const
     */
    "REFUND_FAILED": "REFUND_FAILED",
    /**
     * value: "REFUNDED_REVERSED"
     * @const
     */
    "REFUNDED_REVERSED": "REFUNDED_REVERSED",
    /**
     * value: "PAIDOUT_REVERSED"
     * @const
     */
    "PAIDOUT_REVERSED": "PAIDOUT_REVERSED",
    /**
     * value: "VOID_PENDING_REFUND"
     * @const
     */
    "VOID_PENDING_REFUND": "VOID_PENDING_REFUND",
    /**
     * value: "POSTPONED_REFUND"
     * @const
     */
    "POSTPONED_REFUND": "POSTPONED_REFUND",
    /**
     * value: "REQUEST_FOR_INFORMATION"
     * @const
     */
    "REQUEST_FOR_INFORMATION": "REQUEST_FOR_INFORMATION",
    /**
     * value: "CHARGEBACK"
     * @const
     */
    "CHARGEBACK": "CHARGEBACK",
    /**
     * value: "CHARGEBACK_REVERSED"
     * @const
     */
    "CHARGEBACK_REVERSED": "CHARGEBACK_REVERSED",
    /**
     * value: "NOTIFICATION_OF_CHARGEBACK"
     * @const
     */
    "NOTIFICATION_OF_CHARGEBACK": "NOTIFICATION_OF_CHARGEBACK",
    /**
     * value: "NOTIFICATION_OF_FRAUD"
     * @const
     */
    "NOTIFICATION_OF_FRAUD": "NOTIFICATION_OF_FRAUD",
    /**
     * value: "MANUAL_REVIEW_ACCEPT"
     * @const
     */
    "MANUAL_REVIEW_ACCEPT": "MANUAL_REVIEW_ACCEPT",
    /**
     * value: "MANUAL_REVIEW_REJECT"
     * @const
     */
    "MANUAL_REVIEW_REJECT": "MANUAL_REVIEW_REJECT",
    /**
     * value: "RECURRING_CONTRACT"
     * @const
     */
    "RECURRING_CONTRACT": "RECURRING_CONTRACT",
    /**
     * value: "PAYOUT_EXPIRE"
     * @const
     */
    "PAYOUT_EXPIRE": "PAYOUT_EXPIRE",
    /**
     * value: "PAYOUT_DECLINE"
     * @const
     */
    "PAYOUT_DECLINE": "PAYOUT_DECLINE",
    /**
     * value: "PAYOUT_THIRDPARTY"
     * @const
     */
    "PAYOUT_THIRDPARTY": "PAYOUT_THIRDPARTY",
    /**
     * value: "REFUND_WITH_DATA"
     * @const
     */
    "REFUND_WITH_DATA": "REFUND_WITH_DATA",
    /**
     * value: "AUTHORISE_REFERRAL"
     * @const
     */
    "AUTHORISE_REFERRAL": "AUTHORISE_REFERRAL",
    /**
     * value: "FRAUD_ONLY"
     * @const
     */
    "FRAUD_ONLY": "FRAUD_ONLY",
    /**
     * value: "FUND_TRANSFER"
     * @const
     */
    "FUND_TRANSFER": "FUND_TRANSFER",
    /**
     * value: "HANDLED_EXTERNALLY"
     * @const
     */
    "HANDLED_EXTERNALLY": "HANDLED_EXTERNALLY",
    /**
     * value: "OFFER_CLOSED"
     * @const
     */
    "OFFER_CLOSED": "OFFER_CLOSED",
    /**
     * value: "ORDER_OPENED"
     * @const
     */
    "ORDER_OPENED": "ORDER_OPENED",
    /**
     * value: "ORDER_CLOSED"
     * @const
     */
    "ORDER_CLOSED": "ORDER_CLOSED",
    /**
     * value: "PENDING"
     * @const
     */
    "PENDING": "PENDING",
    /**
     * value: "PROCESS_RETRY"
     * @const
     */
    "PROCESS_RETRY": "PROCESS_RETRY",
    /**
     * value: "REPORT_AVAILABLE"
     * @const
     */
    "REPORT_AVAILABLE": "REPORT_AVAILABLE"  };

  /**
   * Returns a <code>EventCode</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/EventCode} The enum <code>EventCode</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


