/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 25
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FraudCheckResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FraudCheckResult'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenApiJs) {
      root.AdyenApiJs = {};
    }
    root.AdyenApiJs.FraudResult = factory(root.AdyenApiJs.ApiClient, root.AdyenApiJs.FraudCheckResult);
  }
}(this, function(ApiClient, FraudCheckResult) {
  'use strict';




  /**
   * The FraudResult model module.
   * @module model/FraudResult
   * @version 1.25.1
   */

  /**
   * Constructs a new <code>FraudResult</code>.
   * the fraud result properties of the payment
   * @alias module:model/FraudResult
   * @class
   * @param accountScore {Number} the total fraud score generated by the risk checks
   */
  var exports = function(accountScore) {
    var _this = this;

    _this['accountScore'] = accountScore;

  };

  /**
   * Constructs a <code>FraudResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FraudResult} obj Optional instance to populate.
   * @return {module:model/FraudResult} The populated <code>FraudResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accountScore')) {
        obj['accountScore'] = ApiClient.convertToType(data['accountScore'], 'Number');
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [FraudCheckResult]);
      }
    }
    return obj;
  }

  /**
   * the total fraud score generated by the risk checks
   * @member {Number} accountScore
   */
  exports.prototype['accountScore'] = undefined;
  /**
   * the result of the individual risk checks
   * @member {Array.<module:model/FraudCheckResult>} results
   */
  exports.prototype['results'] = undefined;


  /**
   * Returns the total fraud score generated by the risk checks
   * @return {Number}
   */
  exports.prototype.getAccountScore = function() {
    return this['accountScore'];
  }

  /**
   * Sets the total fraud score generated by the risk checks
   * @param {Number} accountScore the total fraud score generated by the risk checks
   */
  exports.prototype.setAccountScore = function(accountScore) {
    this['accountScore'] = accountScore;
  }


  /**
   * Returns the result of the individual risk checks
   * @return {Array.<module:model/FraudCheckResult>}
   */
  exports.prototype.getResults = function() {
    return this['results'];
  }

  /**
   * Sets the result of the individual risk checks
   * @param {Array.<module:model/FraudCheckResult>} results the result of the individual risk checks
   */
  exports.prototype.setResults = function(results) {
    this['results'] = results;
  }



  return exports;
}));


