/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 18
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenApiJs) {
      root.AdyenApiJs = {};
    }
    root.AdyenApiJs.Installments = factory(root.AdyenApiJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Installments model module.
   * @module model/Installments
   * @version 1.18.1
   */

  /**
   * Constructs a new <code>Installments</code>.
   * the installment properties of the payment
   * @alias module:model/Installments
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>Installments</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Installments} obj Optional instance to populate.
   * @return {module:model/Installments} The populated <code>Installments</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'Number');
      }
    }
    return obj;
  }

  /**
   * the number of installments in which the payment will be divided
   * @member {Number} value
   */
  exports.prototype['value'] = undefined;


  /**
   * Returns the number of installments in which the payment will be divided
   * @return {Number}
   */
  exports.prototype.getValue = function() {
    return this['value'];
  }

  /**
   * Sets the number of installments in which the payment will be divided
   * @param {Number} value the number of installments in which the payment will be divided
   */
  exports.prototype.setValue = function(value) {
    this['value'] = value;
  }



  return exports;
}));


