/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenApiJs) {
      root.AdyenApiJs = {};
    }
    root.AdyenApiJs.PayoutResultCodeType = factory(root.AdyenApiJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class PayoutResultCodeType.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "[payout-confirm-received]"
     * @const
     */
    "[payout-confirm-received]": "[payout-confirm-received]",
    /**
     * value: "[payout-submit-received]"
     * @const
     */
    "[payout-submit-received]": "[payout-submit-received]",
    /**
     * value: "[payout-decline-received]"
     * @const
     */
    "[payout-decline-received]": "[payout-decline-received]"  };

  /**
   * Returns a <code>PayoutResultCodeType</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/PayoutResultCodeType} The enum <code>PayoutResultCodeType</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


