/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Recurring'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Recurring'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenApiJs) {
      root.AdyenApiJs = {};
    }
    root.AdyenApiJs.RecurringDetailsRequest = factory(root.AdyenApiJs.ApiClient, root.AdyenApiJs.Recurring);
  }
}(this, function(ApiClient, Recurring) {
  'use strict';




  /**
   * The RecurringDetailsRequest model module.
   * @module model/RecurringDetailsRequest
   * @version 1.30.5
   */

  /**
   * Constructs a new <code>RecurringDetailsRequest</code>.
   * @alias module:model/RecurringDetailsRequest
   * @class
   * @param merchantAccount {String} The merchant account identifier you want to process the (transaction) request with.
   * @param shopperReference {String} The reference you use to uniquely identify the shopper (e.g. user ID or account ID).
   */
  var exports = function(merchantAccount, shopperReference) {
    var _this = this;

    _this['merchantAccount'] = merchantAccount;

    _this['shopperReference'] = shopperReference;
  };

  /**
   * Constructs a <code>RecurringDetailsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecurringDetailsRequest} obj Optional instance to populate.
   * @return {module:model/RecurringDetailsRequest} The populated <code>RecurringDetailsRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('merchantAccount')) {
        obj['merchantAccount'] = ApiClient.convertToType(data['merchantAccount'], 'String');
      }
      if (data.hasOwnProperty('recurring')) {
        obj['recurring'] = Recurring.constructFromObject(data['recurring']);
      }
      if (data.hasOwnProperty('shopperReference')) {
        obj['shopperReference'] = ApiClient.convertToType(data['shopperReference'], 'String');
      }
    }
    return obj;
  }

  /**
   * The merchant account identifier you want to process the (transaction) request with.
   * @member {String} merchantAccount
   */
  exports.prototype['merchantAccount'] = undefined;
  /**
   * @member {module:model/Recurring} recurring
   */
  exports.prototype['recurring'] = undefined;
  /**
   * The reference you use to uniquely identify the shopper (e.g. user ID or account ID).
   * @member {String} shopperReference
   */
  exports.prototype['shopperReference'] = undefined;


  /**
   * Returns The merchant account identifier you want to process the (transaction) request with.
   * @return {String}
   */
  exports.prototype.getMerchantAccount = function() {
    return this['merchantAccount'];
  }

  /**
   * Sets The merchant account identifier you want to process the (transaction) request with.
   * @param {String} merchantAccount The merchant account identifier you want to process the (transaction) request with.
   */
  exports.prototype.setMerchantAccount = function(merchantAccount) {
    this['merchantAccount'] = merchantAccount;
  }


  /**
   * @return {module:model/Recurring}
   */
  exports.prototype.getRecurring = function() {
    return this['recurring'];
  }

  /**
   * @param {module:model/Recurring} recurring
   */
  exports.prototype.setRecurring = function(recurring) {
    this['recurring'] = recurring;
  }


  /**
   * Returns The reference you use to uniquely identify the shopper (e.g. user ID or account ID).
   * @return {String}
   */
  exports.prototype.getShopperReference = function() {
    return this['shopperReference'];
  }

  /**
   * Sets The reference you use to uniquely identify the shopper (e.g. user ID or account ID).
   * @param {String} shopperReference The reference you use to uniquely identify the shopper (e.g. user ID or account ID).
   */
  exports.prototype.setShopperReference = function(shopperReference) {
    this['shopperReference'] = shopperReference;
  }



  return exports;
}));


