/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AdyenApiJs) {
      root.AdyenApiJs = {};
    }
    root.AdyenApiJs.StoreDetailAndSubmitResult = factory(root.AdyenApiJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The StoreDetailAndSubmitResult model module.
   * @module model/StoreDetailAndSubmitResult
   * @version 1.30.3
   */

  /**
   * Constructs a new <code>StoreDetailAndSubmitResult</code>.
   * @alias module:model/StoreDetailAndSubmitResult
   * @class
   * @param pspReference {String} the unique identifier assigned to this modification. This reference is the pspReference of the payout.
   * @param resultCode {String} In case of success, it is payout-submit-received. In case of an error, an informational message is returned.
   */
  var exports = function(pspReference, resultCode) {
    var _this = this;


    _this['pspReference'] = pspReference;
    _this['resultCode'] = resultCode;

  };

  /**
   * Constructs a <code>StoreDetailAndSubmitResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StoreDetailAndSubmitResult} obj Optional instance to populate.
   * @return {module:model/StoreDetailAndSubmitResult} The populated <code>StoreDetailAndSubmitResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('additionalData')) {
        obj['additionalData'] = ApiClient.convertToType(data['additionalData'], Object);
      }
      if (data.hasOwnProperty('pspReference')) {
        obj['pspReference'] = ApiClient.convertToType(data['pspReference'], 'String');
      }
      if (data.hasOwnProperty('resultCode')) {
        obj['resultCode'] = ApiClient.convertToType(data['resultCode'], 'String');
      }
      if (data.hasOwnProperty('refusalReason')) {
        obj['refusalReason'] = ApiClient.convertToType(data['refusalReason'], 'String');
      }
    }
    return obj;
  }

  /**
   * This field contains additional data, which may be returned in a particular response.
   * @member {Object} additionalData
   */
  exports.prototype['additionalData'] = undefined;
  /**
   * the unique identifier assigned to this modification. This reference is the pspReference of the payout.
   * @member {String} pspReference
   */
  exports.prototype['pspReference'] = undefined;
  /**
   * In case of success, it is payout-submit-received. In case of an error, an informational message is returned.
   * @member {String} resultCode
   */
  exports.prototype['resultCode'] = undefined;
  /**
   * In case of refusal, an informational message for the reason.
   * @member {String} refusalReason
   */
  exports.prototype['refusalReason'] = undefined;


  /**
   * Returns This field contains additional data, which may be returned in a particular response.
   * @return {Object}
   */
  exports.prototype.getAdditionalData = function() {
    return this['additionalData'];
  }

  /**
   * Sets This field contains additional data, which may be returned in a particular response.
   * @param {Object} additionalData This field contains additional data, which may be returned in a particular response.
   */
  exports.prototype.setAdditionalData = function(additionalData) {
    this['additionalData'] = additionalData;
  }


  /**
   * Returns the unique identifier assigned to this modification. This reference is the pspReference of the payout.
   * @return {String}
   */
  exports.prototype.getPspReference = function() {
    return this['pspReference'];
  }

  /**
   * Sets the unique identifier assigned to this modification. This reference is the pspReference of the payout.
   * @param {String} pspReference the unique identifier assigned to this modification. This reference is the pspReference of the payout.
   */
  exports.prototype.setPspReference = function(pspReference) {
    this['pspReference'] = pspReference;
  }


  /**
   * Returns In case of success, it is payout-submit-received. In case of an error, an informational message is returned.
   * @return {String}
   */
  exports.prototype.getResultCode = function() {
    return this['resultCode'];
  }

  /**
   * Sets In case of success, it is payout-submit-received. In case of an error, an informational message is returned.
   * @param {String} resultCode In case of success, it is payout-submit-received. In case of an error, an informational message is returned.
   */
  exports.prototype.setResultCode = function(resultCode) {
    this['resultCode'] = resultCode;
  }


  /**
   * Returns In case of refusal, an informational message for the reason.
   * @return {String}
   */
  exports.prototype.getRefusalReason = function() {
    return this['refusalReason'];
  }

  /**
   * Sets In case of refusal, an informational message for the reason.
   * @param {String} refusalReason In case of refusal, an informational message for the reason.
   */
  exports.prototype.setRefusalReason = function(refusalReason) {
    this['refusalReason'] = refusalReason;
  }



  return exports;
}));


