/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 18
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AdyenApiJs);
  }
}(this, function(expect, AdyenApiJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AdyenApiJs.BankAccount();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BankAccount', function() {
    it('should create an instance of BankAccount', function() {
      // uncomment below and update the code to test BankAccount
      //var instane = new AdyenApiJs.BankAccount();
      //expect(instance).to.be.a(AdyenApiJs.BankAccount);
    });

    it('should have the property iban (base name: "iban")', function() {
      // uncomment below and update the code to test the property iban
      //var instane = new AdyenApiJs.BankAccount();
      //expect(instance).to.be();
    });

    it('should have the property ownerName (base name: "ownerName")', function() {
      // uncomment below and update the code to test the property ownerName
      //var instane = new AdyenApiJs.BankAccount();
      //expect(instance).to.be();
    });

    it('should have the property bankName (base name: "bankName")', function() {
      // uncomment below and update the code to test the property bankName
      //var instane = new AdyenApiJs.BankAccount();
      //expect(instance).to.be();
    });

    it('should have the property taxId (base name: "taxId")', function() {
      // uncomment below and update the code to test the property taxId
      //var instane = new AdyenApiJs.BankAccount();
      //expect(instance).to.be();
    });

    it('should have the property bankCity (base name: "bankCity")', function() {
      // uncomment below and update the code to test the property bankCity
      //var instane = new AdyenApiJs.BankAccount();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "countryCode")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instane = new AdyenApiJs.BankAccount();
      //expect(instance).to.be();
    });

    it('should have the property bankAccountNumber (base name: "bankAccountNumber")', function() {
      // uncomment below and update the code to test the property bankAccountNumber
      //var instane = new AdyenApiJs.BankAccount();
      //expect(instance).to.be();
    });

    it('should have the property bankLocationId (base name: "bankLocationId")', function() {
      // uncomment below and update the code to test the property bankLocationId
      //var instane = new AdyenApiJs.BankAccount();
      //expect(instance).to.be();
    });

    it('should have the property bic (base name: "bic")', function() {
      // uncomment below and update the code to test the property bic
      //var instane = new AdyenApiJs.BankAccount();
      //expect(instance).to.be();
    });

  });

}));
