/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 30
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AdyenApiJs);
  }
}(this, function(expect, AdyenApiJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AdyenApiJs.ModificationRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModificationRequest', function() {
    it('should create an instance of ModificationRequest', function() {
      // uncomment below and update the code to test ModificationRequest
      //var instane = new AdyenApiJs.ModificationRequest();
      //expect(instance).to.be.a(AdyenApiJs.ModificationRequest);
    });

    it('should have the property reference (base name: "reference")', function() {
      // uncomment below and update the code to test the property reference
      //var instane = new AdyenApiJs.ModificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property modificationAmount (base name: "modificationAmount")', function() {
      // uncomment below and update the code to test the property modificationAmount
      //var instane = new AdyenApiJs.ModificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property authorisationCode (base name: "authorisationCode")', function() {
      // uncomment below and update the code to test the property authorisationCode
      //var instane = new AdyenApiJs.ModificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property originalReference (base name: "originalReference")', function() {
      // uncomment below and update the code to test the property originalReference
      //var instane = new AdyenApiJs.ModificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property merchantAccount (base name: "merchantAccount")', function() {
      // uncomment below and update the code to test the property merchantAccount
      //var instane = new AdyenApiJs.ModificationRequest();
      //expect(instance).to.be();
    });

    it('should have the property additionalData (base name: "additionalData")', function() {
      // uncomment below and update the code to test the property additionalData
      //var instane = new AdyenApiJs.ModificationRequest();
      //expect(instance).to.be();
    });

  });

}));
