/**
 * Adyen api
 * Operations about payments, recurring and payout
 *
 * OpenAPI spec version: 25
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AdyenApiJs);
  }
}(this, function(expect, AdyenApiJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AdyenApiJs.RecurringDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RecurringDetail', function() {
    it('should create an instance of RecurringDetail', function() {
      // uncomment below and update the code to test RecurringDetail
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be.a(AdyenApiJs.RecurringDetail);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property creationDate (base name: "creationDate")', function() {
      // uncomment below and update the code to test the property creationDate
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property card (base name: "card")', function() {
      // uncomment below and update the code to test the property card
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property billingAddress (base name: "billingAddress")', function() {
      // uncomment below and update the code to test the property billingAddress
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property additionalData (base name: "additionalData")', function() {
      // uncomment below and update the code to test the property additionalData
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property shopperName (base name: "shopperName")', function() {
      // uncomment below and update the code to test the property shopperName
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property socialSecurityNumber (base name: "socialSecurityNumber")', function() {
      // uncomment below and update the code to test the property socialSecurityNumber
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property recurringDetailReference (base name: "recurringDetailReference")', function() {
      // uncomment below and update the code to test the property recurringDetailReference
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property bank (base name: "bank")', function() {
      // uncomment below and update the code to test the property bank
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property alias (base name: "alias")', function() {
      // uncomment below and update the code to test the property alias
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property aliasType (base name: "aliasType")', function() {
      // uncomment below and update the code to test the property aliasType
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property variant (base name: "variant")', function() {
      // uncomment below and update the code to test the property variant
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethodVariant (base name: "paymentMethodVariant")', function() {
      // uncomment below and update the code to test the property paymentMethodVariant
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property firstPspReference (base name: "firstPspReference")', function() {
      // uncomment below and update the code to test the property firstPspReference
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property contractTypes (base name: "contractTypes")', function() {
      // uncomment below and update the code to test the property contractTypes
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property acquirer (base name: "acquirer")', function() {
      // uncomment below and update the code to test the property acquirer
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

    it('should have the property acquirerAccount (base name: "acquirerAccount")', function() {
      // uncomment below and update the code to test the property acquirerAccount
      //var instane = new AdyenApiJs.RecurringDetail();
      //expect(instance).to.be();
    });

  });

}));
